### ISSUE TITLE
Throws strings instead of errors

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/n-webpack#8]
This is causing undebuggable problems for me

https://github.com/Financial-Times/n-webpack/blob/2cc57ebb8884a2005c48df370dcf7508643265c0/lib/addons/verify-build.js#L40-L50

**Comment by wheresrhys** [comment]
I _think_ @i-like-robots fixed this

**Comment by i-like-robots** [comment]
https://github.com/Financial-Times/n-webpack/pull/7
